//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dfdfdf_1112
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График отпуск.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикОтпуск CustomAttributes)

    // *** End programmer edit section *** (ГрафикОтпуск CustomAttributes)
    [AutoAltered()]
    [Caption("График отпуск")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикОтпускE", new string[] {
            "НомерДок as \'Номер док\'",
            "Дата as \'Дата\'",
            "ДатаНач as \'Дата нач\'",
            "КолДней as \'Кол дней\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("ГрафикОтпускE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ГрафикОтпускL", new string[] {
            "НомерДок as \'Номер док\'",
            "Дата as \'Дата\'",
            "ДатаНач as \'Дата нач\'",
            "КолДней as \'Кол дней\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class ГрафикОтпуск : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерДок;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private System.DateTime fДатаНач;
        
        private int fКолДней;
        
        private IIS.Dfdfdf_1112.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ГрафикОтпуск CustomMembers)

        // *** End programmer edit section *** (ГрафикОтпуск CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.Дата CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.Дата Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ГрафикОтпуск.Дата Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.Дата Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.Дата Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.Дата Set end)
            }
        }
        
        /// <summary>
        /// ДатаНач.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.ДатаНач CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.ДатаНач CustomAttributes)
        public virtual System.DateTime ДатаНач
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаНач Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаНач Get start)
                System.DateTime result = this.fДатаНач;
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаНач Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаНач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаНач Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаНач Set start)
                this.fДатаНач = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаНач Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаНач Set end)
            }
        }
        
        /// <summary>
        /// КолДней.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.КолДней CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.КолДней CustomAttributes)
        public virtual int КолДней
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.КолДней Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.КолДней Get start)
                int result = this.fКолДней;
                // *** Start programmer edit section *** (ГрафикОтпуск.КолДней Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.КолДней Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.КолДней Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.КолДней Set start)
                this.fКолДней = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.КолДней Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.КолДней Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.НомерДок CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.НомерДок CustomAttributes)
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.НомерДок Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (ГрафикОтпуск.НомерДок Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.НомерДок Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.НомерДок Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// График отпуск.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Dfdfdf_1112.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.Сотрудники Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.Сотрудники Get start)
                IIS.Dfdfdf_1112.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ГрафикОтпуск.Сотрудники Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.Сотрудники Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.Сотрудники Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикОтпускE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикОтпускE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикОтпускE", typeof(IIS.Dfdfdf_1112.ГрафикОтпуск));
                }
            }
            
            /// <summary>
            /// "ГрафикОтпускL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикОтпускL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикОтпускL", typeof(IIS.Dfdfdf_1112.ГрафикОтпуск));
                }
            }
        }
    }
}
