//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dfdfdf_1112
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчетный лист.
    /// </summary>
    // *** Start programmer edit section *** (РасчетныйЛист CustomAttributes)

    // *** End programmer edit section *** (РасчетныйЛист CustomAttributes)
    [AutoAltered()]
    [Caption("Расчетный лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетныйЛистE", new string[] {
            "НомерЛиста as \'Номер листа\'",
            "Дата as \'Дата\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [AssociatedDetailViewAttribute("РасчетныйЛистE", "Тч", "ТчE", true, "", "Тч", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РасчетныйЛистE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("РасчетныйЛистL", new string[] {
            "НомерЛиста as \'Номер листа\'",
            "Дата as \'Дата\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class РасчетныйЛист : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЛиста;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Dfdfdf_1112.Сотрудники fСотрудники;
        
        private IIS.Dfdfdf_1112.DetailArrayOfТч fТч;
        
        // *** Start programmer edit section *** (РасчетныйЛист CustomMembers)

        // *** End programmer edit section *** (РасчетныйЛист CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Дата CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерЛиста.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.НомерЛиста CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.НомерЛиста CustomAttributes)
        public virtual int НомерЛиста
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.НомерЛиста Get start)

                // *** End programmer edit section *** (РасчетныйЛист.НомерЛиста Get start)
                int result = this.fНомерЛиста;
                // *** Start programmer edit section *** (РасчетныйЛист.НомерЛиста Get end)

                // *** End programmer edit section *** (РасчетныйЛист.НомерЛиста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.НомерЛиста Set start)

                // *** End programmer edit section *** (РасчетныйЛист.НомерЛиста Set start)
                this.fНомерЛиста = value;
                // *** Start programmer edit section *** (РасчетныйЛист.НомерЛиста Set end)

                // *** End programmer edit section *** (РасчетныйЛист.НомерЛиста Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Dfdfdf_1112.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Get start)
                IIS.Dfdfdf_1112.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Тч CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Тч CustomAttributes)
        public virtual IIS.Dfdfdf_1112.DetailArrayOfТч Тч
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Тч Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Тч Get start)
                if ((this.fТч == null))
                {
                    this.fТч = new IIS.Dfdfdf_1112.DetailArrayOfТч(this);
                }
                IIS.Dfdfdf_1112.DetailArrayOfТч result = this.fТч;
                // *** Start programmer edit section *** (РасчетныйЛист.Тч Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Тч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Тч Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Тч Set start)
                this.fТч = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Тч Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Тч Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетныйЛистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетныйЛистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетныйЛистE", typeof(IIS.Dfdfdf_1112.РасчетныйЛист));
                }
            }
            
            /// <summary>
            /// "РасчетныйЛистL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетныйЛистL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетныйЛистL", typeof(IIS.Dfdfdf_1112.РасчетныйЛист));
                }
            }
        }
    }
}
