//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dfdfdf_1112
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Согласие опд.
    /// </summary>
    // *** Start programmer edit section *** (СогласиеОпд CustomAttributes)

    // *** End programmer edit section *** (СогласиеОпд CustomAttributes)
    [AutoAltered()]
    [Caption("Согласие опд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СогласиеОпдE", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("СогласиеОпдE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("СогласиеОпдL", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class СогласиеОпд : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Dfdfdf_1112.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (СогласиеОпд CustomMembers)

        // *** End programmer edit section *** (СогласиеОпд CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (СогласиеОпд.Дата CustomAttributes)

        // *** End programmer edit section *** (СогласиеОпд.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (СогласиеОпд.Дата Get start)

                // *** End programmer edit section *** (СогласиеОпд.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (СогласиеОпд.Дата Get end)

                // *** End programmer edit section *** (СогласиеОпд.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СогласиеОпд.Дата Set start)

                // *** End programmer edit section *** (СогласиеОпд.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (СогласиеОпд.Дата Set end)

                // *** End programmer edit section *** (СогласиеОпд.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (СогласиеОпд.Номер CustomAttributes)

        // *** End programmer edit section *** (СогласиеОпд.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (СогласиеОпд.Номер Get start)

                // *** End programmer edit section *** (СогласиеОпд.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (СогласиеОпд.Номер Get end)

                // *** End programmer edit section *** (СогласиеОпд.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СогласиеОпд.Номер Set start)

                // *** End programmer edit section *** (СогласиеОпд.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (СогласиеОпд.Номер Set end)

                // *** End programmer edit section *** (СогласиеОпд.Номер Set end)
            }
        }
        
        /// <summary>
        /// Согласие опд.
        /// </summary>
        // *** Start programmer edit section *** (СогласиеОпд.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (СогласиеОпд.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Dfdfdf_1112.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (СогласиеОпд.Сотрудники Get start)

                // *** End programmer edit section *** (СогласиеОпд.Сотрудники Get start)
                IIS.Dfdfdf_1112.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (СогласиеОпд.Сотрудники Get end)

                // *** End programmer edit section *** (СогласиеОпд.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СогласиеОпд.Сотрудники Set start)

                // *** End programmer edit section *** (СогласиеОпд.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (СогласиеОпд.Сотрудники Set end)

                // *** End programmer edit section *** (СогласиеОпд.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СогласиеОпдE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеОпдE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеОпдE", typeof(IIS.Dfdfdf_1112.СогласиеОпд));
                }
            }
            
            /// <summary>
            /// "СогласиеОпдL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеОпдL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеОпдL", typeof(IIS.Dfdfdf_1112.СогласиеОпд));
                }
            }
        }
    }
}
