//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dfdfdf_1112
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч.
    /// </summary>
    // *** Start programmer edit section *** (Тч CustomAttributes)

    // *** End programmer edit section *** (Тч CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчE", new string[] {
            "Тип as \'Тип\'",
            "Наименование as \'Наименование\'",
            "Ндфл as \'Ндфл\'",
            "Взносы as \'Взносы\'",
            "Сумма as \'Сумма\'"})]
    public class Тч : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Dfdfdf_1112.Тип fТип;
        
        private string fНаименование;
        
        private double fНдфл;
        
        private double fВзносы;
        
        private double fСумма;
        
        private IIS.Dfdfdf_1112.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (Тч CustomMembers)

        // *** End programmer edit section *** (Тч CustomMembers)

        
        /// <summary>
        /// Взносы.
        /// </summary>
        // *** Start programmer edit section *** (Тч.Взносы CustomAttributes)

        // *** End programmer edit section *** (Тч.Взносы CustomAttributes)
        public virtual double Взносы
        {
            get
            {
                // *** Start programmer edit section *** (Тч.Взносы Get start)

                // *** End programmer edit section *** (Тч.Взносы Get start)
                double result = this.fВзносы;
                // *** Start programmer edit section *** (Тч.Взносы Get end)

                // *** End programmer edit section *** (Тч.Взносы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч.Взносы Set start)

                // *** End programmer edit section *** (Тч.Взносы Set start)
                this.fВзносы = value;
                // *** Start programmer edit section *** (Тч.Взносы Set end)

                // *** End programmer edit section *** (Тч.Взносы Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Тч.Наименование CustomAttributes)

        // *** End programmer edit section *** (Тч.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Тч.Наименование Get start)

                // *** End programmer edit section *** (Тч.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Тч.Наименование Get end)

                // *** End programmer edit section *** (Тч.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч.Наименование Set start)

                // *** End programmer edit section *** (Тч.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Тч.Наименование Set end)

                // *** End programmer edit section *** (Тч.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Ндфл.
        /// </summary>
        // *** Start programmer edit section *** (Тч.Ндфл CustomAttributes)

        // *** End programmer edit section *** (Тч.Ндфл CustomAttributes)
        public virtual double Ндфл
        {
            get
            {
                // *** Start programmer edit section *** (Тч.Ндфл Get start)

                // *** End programmer edit section *** (Тч.Ндфл Get start)
                double result = this.fНдфл;
                // *** Start programmer edit section *** (Тч.Ндфл Get end)

                // *** End programmer edit section *** (Тч.Ндфл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч.Ндфл Set start)

                // *** End programmer edit section *** (Тч.Ндфл Set start)
                this.fНдфл = value;
                // *** Start programmer edit section *** (Тч.Ндфл Set end)

                // *** End programmer edit section *** (Тч.Ндфл Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Тч.Сумма CustomAttributes)

        // *** End programmer edit section *** (Тч.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Тч.Сумма Get start)

                // *** End programmer edit section *** (Тч.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Тч.Сумма Get end)

                // *** End programmer edit section *** (Тч.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч.Сумма Set start)

                // *** End programmer edit section *** (Тч.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Тч.Сумма Set end)

                // *** End programmer edit section *** (Тч.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Тч.Тип CustomAttributes)

        // *** End programmer edit section *** (Тч.Тип CustomAttributes)
        public virtual IIS.Dfdfdf_1112.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (Тч.Тип Get start)

                // *** End programmer edit section *** (Тч.Тип Get start)
                IIS.Dfdfdf_1112.Тип result = this.fТип;
                // *** Start programmer edit section *** (Тч.Тип Get end)

                // *** End programmer edit section *** (Тч.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч.Тип Set start)

                // *** End programmer edit section *** (Тч.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Тч.Тип Set end)

                // *** End programmer edit section *** (Тч.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Dfdfdf_1112.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (Тч.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (Тч.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.Dfdfdf_1112.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (Тч.РасчетныйЛист Get start)

                // *** End programmer edit section *** (Тч.РасчетныйЛист Get start)
                IIS.Dfdfdf_1112.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (Тч.РасчетныйЛист Get end)

                // *** End programmer edit section *** (Тч.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч.РасчетныйЛист Set start)

                // *** End programmer edit section *** (Тч.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (Тч.РасчетныйЛист Set end)

                // *** End programmer edit section *** (Тч.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчE", typeof(IIS.Dfdfdf_1112.Тч));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Тч.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТч CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТч CustomAttributes)
    public class DetailArrayOfТч : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Dfdfdf_1112.DetailArrayOfТч members)

        // *** End programmer edit section *** (IIS.Dfdfdf_1112.DetailArrayOfТч members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Тч by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Тч.
        /// </summary>
        public DetailArrayOfТч(IIS.Dfdfdf_1112.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(Тч), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.Dfdfdf_1112.Тч this[int index]
        {
            get
            {
                return ((IIS.Dfdfdf_1112.Тч)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Dfdfdf_1112.Тч dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
